### ISSUE TITLE
青龙面板报错，我这是少了啥吗

### ISSUE THREAD

**Issue by yingfeng-i** [Clannad-233/CheckIn_BaiduTieba#1]
`## 开始执行... 2023-12-17 18:02:49

开始签到
2023-12-17 18:02:49,990 - INFO - 获取tbs开始
2023-12-17 18:02:50,061 - INFO - 获取tbs结束
2023-12-17 18:02:50,062 - INFO - 获取关注的贴吧开始
2023-12-17 18:02:50,280 - INFO - 获取关注的贴吧结束
2023-12-17 18:02:50,281 - INFO - 开始签到贴吧：****（我删掉了，这里正常获取到了一个贴吧名）
Traceback (most recent call last):
  File "/ql/data/scripts/Tieba/Tieba_Sgin_yingfeng.swap.py", line 222, in <module>
    main()
  File "/ql/data/scripts/Tieba/Tieba_Sgin_yingfeng.swap.py", line 211, in main
    client_sign(b, tbs, j["id"], j["name"])
  File "/ql/data/scripts/Tieba/Tieba_Sgin_yingfeng.swap.py", line 185, in client_sign
    tbs = getTbs(kw)
  File "/ql/data/scripts/Tieba/Tieba_Sgin_yingfeng.swap.py", line 167, in getTbs
    response = requests.get(url, headers=HEADERS)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 394, in request
    self.putheader(header, value)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 308, in putheader
    super().putheader(header, *values)
  File "/usr/local/lib/python3.10/http/client.py", line 1256, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

## 执行结束... 2023-12-17 18:02:50  耗时 1 秒　　　　　`

**Comment by yingfeng-i** [comment]
cookie那边很长，是不是只要其中的某个
BAIDUID=***************; BIDUPSID=*******************; PSTM=*******************;
